# Generated by Django 4.0.5 on 2022-06-08 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Please type in the title of this blog post', max_length=200, verbose_name='Blog Post Title')),
                ('sub_title', models.CharField(blank=True, help_text='Enter a descriptive subheading, so that readers can have a better idea what the blog post is about.', max_length=400, null=True, verbose_name='Sub heading for the blog post')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('content', models.TextField(help_text='Enter in the content for the blog post.', max_length=100000)),
                ('blog_author', models.ManyToManyField(to='blog.author')),
            ],
            options={
                'ordering': ['-last_modified'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='Please write a concise comment about the blog post.', max_length=1000)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost')),
            ],
        ),
    ]
