# Generated by Django 4.0.5 on 2022-06-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['last_modified']},
        ),
    ]
