# Generated by Django 4.0.5 on 2022-06-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_options_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_born',
            field=models.DateField(help_text='Please enter in the date you were born.', null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='short_bio',
            field=models.TextField(help_text='In a few words, describe yourself.', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Enter in the content for the blog post.', max_length=1000000),
        ),
    ]
