# Generated by Django 4.0.5 on 2022-06-12 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_author_blog_user_alter_comment_content_hit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='blog_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
